apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: bmif
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bmif
    app.kubernetes.io/part-of: byoc-app-ucgy
  name: bmifgdvg
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: bmif
    weight: null
status: {}
